#!/usr/bin/python3
import random as rnd
def randompass(length):
  array = range(97, 123)
  array2 = range(65, 90)
  array3 = range(33, 46)
  realarray = []
  for x, y, z in zip(array, array2, array3):
    realarray.append(x)
    realarray.append(y)
    realarray.append(z)
  passwordis = []
  number = 1
  while number <= length:
    passwordis.append(chr(rnd.choice(realarray)))
    number = number + 1
  newpassword = "".join(passwordis)
  return newpassword

print(randompass(20))

#Wesley Dugan
